"""Dodate veze za istorijat i ostale izmene

Revision ID: 2ec46592d87a
Revises: 857f1fb9c771
Create Date: 2025-06-19 23:07:57.841085

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ec46592d87a'
down_revision: Union[str, None] = '857f1fb9c771'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analize',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('godine', sa.Integer(), nullable=True),
    sa.Column('dijagnoza', sa.String(), nullable=True),
    sa.Column('komorbiditeti', sa.String(), nullable=True),
    sa.Column('pol', sa.String(), nullable=False),
    sa.Column('trudnoca', sa.String(), nullable=True),
    sa.Column('statusi', sa.JSON(), nullable=False),
    sa.Column('uloga', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analize_id'), 'analize', ['id'], unique=False)
    op.add_column('korisnici', sa.Column('uloga', sa.String(), nullable=True))
    op.alter_column('korisnici', 'ime',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('korisnici', 'prezime',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('korisnici', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('korisnici', 'sifra',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.add_column('parametri', sa.Column('korisnik_id', sa.Integer(), nullable=True))
    op.add_column('parametri', sa.Column('dijagnoza', sa.Text(), nullable=True))
    op.create_foreign_key(None, 'parametri', 'korisnici', ['korisnik_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'parametri', type_='foreignkey')
    op.drop_column('parametri', 'dijagnoza')
    op.drop_column('parametri', 'korisnik_id')
    op.alter_column('korisnici', 'sifra',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('korisnici', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('korisnici', 'prezime',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('korisnici', 'ime',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('korisnici', 'uloga')
    op.drop_index(op.f('ix_analize_id'), table_name='analize')
    op.drop_table('analize')
    # ### end Alembic commands ###
