"""Uklonjena kolona uloga iz tabele analize

Revision ID: de546f59e99d
Revises: 92e6b2e2a8d7
Create Date: 2025-07-02 17:53:14.628833

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de546f59e99d'
down_revision: Union[str, None] = '92e6b2e2a8d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analize', sa.Column('alergije', sa.String(), nullable=True))
    op.add_column('parametri', sa.Column('godine', sa.Integer(), nullable=True))
    op.drop_column('parametri', 'starost')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parametri', sa.Column('starost', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('parametri', 'godine')
    op.drop_column('analize', 'alergije')
    # ### end Alembic commands ###
