"""Add korisnik_id to Analiza

Revision ID: ecd6c93649e2
Revises: 629673a3e6ca
Create Date: 2025-07-08 00:00:34.874336

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ecd6c93649e2'
down_revision: Union[str, None] = '629673a3e6ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analize', sa.Column('korisnik_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'analize', 'korisnici', ['korisnik_id'], ['id'])
    op.drop_column('analize', 'uloga')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analize', sa.Column('uloga', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'analize', type_='foreignkey')
    op.drop_column('analize', 'korisnik_id')
    # ### end Alembic commands ###
